//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealoraMedical
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDoktor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblDoktor()
        {
            this.TblRandevus = new HashSet<TblRandevu>();
        }
    
        public string DrSicilNo { get; set; }
        public string DrAd { get; set; }
        public string DrSoyad { get; set; }
        public byte DrBrans { get; set; }
        public string DrSifre { get; set; }
        public short Poliklinik { get; set; }
        public bool Durum { get; set; }
    
        public virtual TblBran TblBran { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblRandevu> TblRandevus { get; set; }
        public virtual TblPoliklinik TblPoliklinik { get; set; }
    }
}
