//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealoraMedical
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDuyuru
    {
        public short DyrID { get; set; }
        public string DyrBaslik { get; set; }
        public string DyrIcerik { get; set; }
        public System.DateTime DyrTarih { get; set; }
    }
}
