//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealoraMedical
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHastaDetayi
    {
        public int HastaDetayiId { get; set; }
        public string HastaTC { get; set; }
        public Nullable<byte> Yas { get; set; }
        public Nullable<byte> Boy { get; set; }
        public Nullable<short> Kg { get; set; }
        public string KanGrubu { get; set; }
        public Nullable<bool> Şeker { get; set; }
        public Nullable<bool> Hipertansiyon { get; set; }
        public Nullable<bool> Hipotansiyon { get; set; }
        public Nullable<bool> Astım { get; set; }
        public Nullable<bool> Hipotiroidi { get; set; }
        public Nullable<bool> Hepatit_B { get; set; }
        public Nullable<bool> Hepatit_C { get; set; }
        public Nullable<bool> HIV { get; set; }
        public Nullable<bool> AIDS { get; set; }
        public Nullable<bool> Depresyon { get; set; }
        public Nullable<bool> Alzheimer { get; set; }
        public Nullable<bool> Epilepsi { get; set; }
        public Nullable<bool> Parkinson { get; set; }
    
        public virtual TblHasta TblHasta { get; set; }
    }
}
