//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealoraMedical
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHastaDetayı
    {
        public int HastaDetayiId { get; set; }
        public string HastaTC { get; set; }
        public byte Yas { get; set; }
        public byte Boy { get; set; }
        public short Kg { get; set; }
        public string KanGrubu { get; set; }
        public bool Şeker { get; set; }
        public bool Hipertansiyon { get; set; }
        public bool Hipotansiyon { get; set; }
        public bool Astım { get; set; }
        public bool Hipotiroidi { get; set; }
        public bool Hepatit_B { get; set; }
        public bool Hepatit_C { get; set; }
        public bool HIV { get; set; }
        public bool AIDS { get; set; }
        public bool Depresyon { get; set; }
        public bool Alzheimer { get; set; }
        public bool Epilepsi { get; set; }
        public bool Parkinson { get; set; }
    
        public virtual TblHasta TblHasta { get; set; }
    }
}
