//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealoraMedical
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblIlac
    {
        public int Id { get; set; }
        public int TedaviID { get; set; }
        public string IlacAd { get; set; }
        public string Dozi { get; set; }
        public string KullanimSekli { get; set; }
        public string Kullanim { get; set; }
        public short Sure { get; set; }
    
        public virtual TblTedavi TblTedavi { get; set; }
    }
}
