//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealoraMedical
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRandevu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblRandevu()
        {
            this.TblTedavis = new HashSet<TblTedavi>();
        }
    
        public int RandevuId { get; set; }
        public string HastaTc { get; set; }
        public string DrSicilNo { get; set; }
        public short PoliklinikNo { get; set; }
        public System.DateTime RandevuTarihi { get; set; }
        public System.TimeSpan RandevuSaati { get; set; }
        public bool Durum { get; set; }
        public Nullable<bool> Geldimi { get; set; }
        public string HastaSikayet { get; set; }
    
        public virtual TblDoktor TblDoktor { get; set; }
        public virtual TblHasta TblHasta { get; set; }
        public virtual TblPoliklinik TblPoliklinik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTedavi> TblTedavis { get; set; }
    }
}
