//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealoraMedical
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSekreter
    {
        public string SktTC { get; set; }
        public string SktAd { get; set; }
        public string SktSoyad { get; set; }
        public string SktTelefon { get; set; }
        public string SktSifre { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
