//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealoraMedical
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTedavi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblTedavi()
        {
            this.TblIlacs = new HashSet<TblIlac>();
        }
    
        public int TedaviID { get; set; }
        public int RandevuID { get; set; }
        public string Teşhis { get; set; }
        public string Tedavi_Yöntemi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblIlac> TblIlacs { get; set; }
        public virtual TblRandevu TblRandevu { get; set; }
    }
}
